### ISSUE TITLE
Optionally increase the verbosity of Webpack config errors

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/roosevelt#1035]
~~Whenever the defined webpack config for a bundle in a roosevelt app is broken, it prints out a stacktrace alongside >5k lines of the parent schema which is the base webpack config. Dependent on the settings for a terminal, it can fill up the history buffer and you cannot scroll up to view the actual error.~~

I propose have a config setting on the bundle object within `js.webpack.bundles` called `verbose` where if true it will print out what is being printed currently, but when set to false, it will only print the main error & stacktrace.

Definitely up for some discussion on cleaning up the errors when Webpack throws errors and other ideas on how we could solve this.

**Comment by kethinov** [comment]
Thanks for filing this, I find it annoying too.

**Comment by kethinov** [comment]
I made the error very concise by default, but it eliminates the ability to see the more verbose version of the error. Reopening this to create a verbose config as @lannonbr described before in case anyone wants that.
