### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#1039]
- `nvm install 16`
- Remove node_modules directory.
- `npm i`
- Stuff breaks.

**Comment by rohit267** [comment]
trying

**Comment by lannonbr** [comment]
So the main thing it seems that is breaking things is `node-sass` not having an updated version yet for Node 16. Also as of last October, there was the [deprecation of `lib-sass`](https://sass-lang.com/blog/libsass-is-deprecated) and subsequently the `node-sass` package, which they'll still support but not add anything new. That said, `dart-sass` has an accompanying npm package titled just `sass`. Tried swapping the packages around and I am currently getting some bugs when running the unit tests dealing with the sass tests that still need to be resolved.

There seems to be other bugs on top of such, but as a glimmer of hope, a clean new project built with `mkroosevelt` installed and works fine.
