### ISSUE TITLE
Integrate a health check library for deployed environments

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#1097]
Integrate a health check library (like [Lightship](https://www.npmjs.com/package/lightship) called out by [Express](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html)) into Roosevelt so applications can easily turn on health check abilities that are used in deployed environments like [Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) and [Docker](https://docs.docker.com/engine/reference/builder/#healthcheck)

**Comment by kethinov** [comment]
Took a closer look at this just now and I don't think this belongs in the framework itself. It's way too tailored to a specific use case and Roosevelt doesn't get in the way if setting it up yourself with the init events.

In the interest of avoiding DRY though, I could totally see something like this being open sourced into its own standalone module that someone could plug and play into Roosevelt. I think this lives in a simlar space to our other standalone modules, like roosevelt-logger.
