### ISSUE TITLE
Possible enhancement: Read Roosevelt defaults from (json) file

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#162]
Example instead of:

```javascript
shutdownTimeout: params.shutdownTimeout || pkg.shutdownTimeout || 30000
```

It would become

```javascript
shutdownTimeout: params.shutdownTimeout || pkg.shutdownTimeout || defaultJsonFile.shutdownTimeout
```

This might make the defaults easier to manage, as well as provide an easy place for users to check and for us to refer to on defaults.

**Comment by kethinov** [comment]
Specifically what we're referring to here is a file dedicated to defining the defaults and sourcing that file in sourceParams as well as the yo generator.

**Comment by alallier** [comment]
Just noting that the generator has a [defaults file](https://github.com/rooseveltframework/generator-roosevelt/blob/dfbfc2814e656a9570d25171da8860487ef0cf7c/rooseveltDefaults.json) already, but it contains specific data useful to the generator might be able to join the files.

**Comment by dishad** [comment]
Going to tackle this by creating and importing a JSON file in `lib`
