### ISSUE TITLE
Parameter priority

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#168]
Right now we have three ways for a Roosevelt [parameter](https://github.com/rooseveltframework/roosevelt#configure-your-app-with-parameters) to be populated:

1. By constructor
2. By package.json
3. By default

The way the [source params](https://github.com/rooseveltframework/roosevelt/blob/000fb668b20e8ea7ffab255fad91e68f8313e471/lib/sourceParams.js) file is designed is to give preference by order of above, first check the constructor, if not in the constructor use the `package.json` and lastly if in neither use the default. This is done by using `||` (or) operators.

Example of enableValidator:

```javascript
enableValidator: params.enableValidator || pkg.rooseveltConfig.enableValidator || false 
```

There is a problem with this logic though. And that is in the case of having a constructor param of `false`, and a `package.json` value of `true`. Using the example from above if I have enableValidtor set to `true` in my pacakge.json but specify `false` in a constructor param, the validator will _always_ be set to true because of the `or` statement. The one line `or` check has the param always source from the `package.json` because of the `false` value and `or` logic.

The validator is set to `false` by default in sample apps but when someone goes to set another param to `false` by constructor but the sample app `package.json` has the value set to `true` this will cause unexpected behavior and results.

_Side note: @kethinov I feel you and I have personally discussed this issue before. I don't think I ever filed an issue for this though. I dug through the issues and didn't find anything in there. If this is a duplicate in any way feel free to close and link_

**Comment by alallier** [comment]
Possible solution:

`someParameter = a !== undefined ? a : b !== undefined ? b : c`

**Comment by dishad** [comment]
going to work on this along with #162

**Comment by JoshL18** [comment]
There is also a problem with object defaults. For example, if a Roosevelt config object is declared in the `package.json`, but does not contain all possible keys, the default will never be assigned on those missing keys. 

Look at this example:
```javascript
validatorExceptions: params.validatorExceptions || pkg.rooseveltConfig.validatorExceptions || {requestHeader: 'Partial', modelValue: '_disableValidator'},
```

If my package.json contains:
```json
"validatorExceptions": {
  "modelValue": "_disableValidator"
}
```

The `sourceParams` file will assign the shown `package.json` object and never assign the default for the `requestHeader` found in `sourceParams`.

**Comment by alallier** [comment]
I believe @JoshL18's comment is still a problem, all keys have to be handled

**Comment by kethinov** [comment]
Not handled by the [latest diff](https://github.com/rooseveltframework/roosevelt/pull/183/files)?

**Comment by alallier** [comment]
No it isn't, the package.json object can still be accepted without all keys, leaving some keys to not be set to default
