### ISSUE TITLE
Merge possible config items together

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#194]
Possible enhancement, merge possible config items together. Right now we split up enabling/disabling of a feature, with it options. Example below:

```JSON
"enableValidator": true,
"htmlValidator": {
  "port": "8888",
  "format": "text"
}
```

_Same with browserify bundling and many others._

I think it might be cleaner to put the enabling/disabling in the same object as the options config.

So the above example would be:

```JSON
"htmlValidator": {
  "enable": true,
  "options": {
    "port": "8888",
    "format": "text"
  }
}
```

So in this new case you would now pass `htmlValidator.options` in place of `htmlValidtor`, which results in the same object being passed as before.

This cuts down on the number of config options and makes it very clear how to enable and configure options. 

What are people's thoughts on this?

Note: This was originally thought of in #193

**Comment by kethinov** [comment]
I think this is a good idea.

Two things to note:

1. I think this should be paired with https://github.com/rooseveltframework/roosevelt/issues/166 and would actually serve as a good test case for it
2. This would warrant a bump of roosevelt from 0.8. to 0.9

**Comment by kethinov** [comment]
- the validator params should get compressed
- js/css compilers: give those a parent so all those different config items like whitelist can live together
- browserify too
- `nodeEnv` and `generateFolderStructure` belong under "App behavior parameters"
- rename `symlinksToStatics` to `staticsSymlinksToPublic`
- rename `versionedStatics` to `versionedPublic`
