### ISSUE TITLE
Bake in support for extra features that some js compilers offer

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/roosevelt#211]
An example feature would be the ability to pass multiple js files worth of code to [UglifyJS](https://github.com/mishoo/UglifyJS2#api-reference) in a single instance of the constructor.

This effort is two-pronged in that it requires work on both roosevelt itself and any compiler module made for roosevelt.

On the module end there would need to be a root level param that exposes support for an optional feature, and roosevelt would be checking for these during the compile step.

**Comment by kethinov** [comment]
This is obviated by the fact that we can create multiple browserify bundles.
