### ISSUE TITLE
Enhancement: HTTPS CA Chain Loading

### ISSUE THREAD

**Issue by jkae** [rooseveltframework/roosevelt#245]
There will, occasionally, be a case where a user would like to create an HTTPS server through Roosevelt -- but instead of a single/multiple file/s that contain a single certificate each, they have one .pem file containing a full chain of certificates.

As it is now, Roosevelt accepts two formats as part of the `config.ca` option:

1. A file path containing a single certificate
2. An array of file paths, each containing a single certificate

We have the following options:

1. If a string (path to a single file) is given as the ca option, we can read it as normal but run it through an additional parsing library like `split-ca`.
2. If reading a file throws `ENOENT`, we can make two assumptions:
 a. The user has passed us a certificate string.
 b. The user has passed us a bad filename.

I don't know how acceptable option 1 is, but 2 seems viable.

In the case of 2a this can either be captured on a case-by-case basis in the loop through `ca[]`, or assumed that the entire array is certificate strings.

In the case of 2b, if we simply set `httpsOptions.ca` to the given value, it's going to throw when attempting to start the server. Since the current behavior throws an error anyway, I don't think that's too big a deal.

**Comment by kethinov** [comment]
Published as 0.9.3.
