### ISSUE TITLE
[minor] HTTPS-Only still attempts to add listener to httpServer

### ISSUE THREAD

**Issue by jkae** [rooseveltframework/roosevelt#249]
**roosevelt.js:106..115**
```
// assign individual keys to connections when opened
httpServer.on('connection', function (conn) {
  let key = conn.remoteAddress + ':' + conn.remotePort
  connections[key] = conn

  // once the connection closes, remove
  conn.on('close', function () {
    delete connections[key]
  })
})
```

When running Roosevelt in `httpsOnly: true`, `httpServer` will not be assigned a value. This call to `httpServer.on` will fail & throw an error.

I also find it interesting that this listener is only active on httpServer connections & ignores httpsServer, though that is likely intentional.

**Comment by kethinov** [comment]
That's definitely a bug.
