### ISSUE TITLE
Improvement: https option object

### ISSUE THREAD

**Issue by jkae** [rooseveltframework/roosevelt#259]
Roll all of the https options into a single object for better clarity. Possible format:

```
"https": {
  "enable": true,
  "httpsOnly": true,
  "port": 443,
  "pfx": true, # delete this
  "keyPath": {
    "pfx": "some/file/path", # use the inclusion of this instead to determine (pfx or key/cert)
    "key": "other/file/path",
    "cert": "next/file/path"
  },
  "passphrase": "pw",
  "ca": ["string", "or", "array"],
  "requestCert": true,
  "rejectUnauthorized": true
}
```

**Comment by alallier** [comment]
This could be done for other parameters as well, like browserify for example. Might be worth it (for someone) to create an issue to encompass all the other parameters that fall under this same type of feel

**Comment by Autre31415** [comment]
[You've already done this a while ago](https://github.com/rooseveltframework/roosevelt/issues/194)

**Comment by alallier** [comment]
Haha I even filed it, I thought I did but missed it this morning my bad on that one
