### ISSUE TITLE
API for scooping up views and exposing them to frontend JS as packaged templates

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#298]
- Off by default
- When enabled:
  - Defaults to whitelisting
  - Should have a whitelist param like:
    ```javascript
    {
      "bundles": {
        "path/to/generated/js/file.js": [ /* list of template files */ ],
        "path/to/other/generated/js/file.js": [ /* list of template files */ ],
        etc...
      }
    }
    ```
  - Should also have a blacklisting param to list templates to always exclude
  - Off by default option to scoop up all templates except those on the blacklist
  - Templates can declare themselves for a bundle Inline at the top line of a given template's source via a code comment containing a special syntax indicating that the template is either whitelisted or blacklisted; this line should be removed once the template is packaged for frontend delivery
    - If a template doesn't declare which bundle it wants to go in, it goes in the first bundle
  - Option to supply middleware to preprocess templates prior to packaging for frontend delivery (useful for some templating systems, e.g. for teddy a dev can optionally run it through a `teddy.compile` before sending to the frontend) 
  - Option to minify template source prior to packaging for frontend delivery (on by default?)
  - Add this comment to the top of all generated JS bundles: `/* do not edit; generated automatically by Roosevelt */`

**Comment by lannonbr** [comment]
I am currently starting work on this.

**Comment by lannonbr** [comment]
@kethinov I have a few questions:

1) You said if a template doesn't declare which bundle it goes in, it will go in the first bundle. Since the bundle syntax is a map, how about there be a default bundle instead of a first bundle?
2) For the blacklist, I think you should be able to specify both specific files to blacklist as well as folders to exclude. Do you think this is alright?

**Comment by kethinov** [comment]
Both of those things sound good.
