### ISSUE TITLE
Explore feasibility of replacing nu validator with HTML Tidy

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#299]
HTML Tidy incidentally validates.

The main focus of the project is formatting/minifying, but a validation functionality exists are part of that.

We need to determine if that validation can be isolated.

On [their documentation](http://www.html-tidy.org/documentation/) if you scroll down to "Running tidy in scripts" there's stuff about warnings and errors. Tidy is designed to fix HTML problems, but it looks like it can report on them as well.

This is a bit indirect, but if it works, it could be a road to getting a much more performant HTML validator in Roosevelt.

Doing this would also close https://github.com/rooseveltframework/roosevelt/issues/35.

**Comment by Autre31415** [comment]
After studying up some more on tidy I've determined that it does not check the boxes that we were looking for with a validator replacement:
- It still requires libraries in additional languages to execute.
- It has no "validate html only mode" and any issues posted against it asking for one don't get responded to positively.
- It implicitly "tidies" the html that it validates in ways that cannot be turned off which in some cases creates false errors and also mangles the line numbers.
