### ISSUE TITLE
Remove aliasing from default npm scripts

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/roosevelt#347]
e.g. `npm run dev` should not just alias to `npm run development` but instead should be a fully copy of the command. This is because aliasing creates bugs/unwanted behavior. Relevant file: https://github.com/rooseveltframework/roosevelt/blob/master/lib/defaults/scripts.json

**Comment by kethinov** [comment]
This is fixed in the generator, but not in the scripts.json
