### ISSUE TITLE
PortScanning for killValidator error (refactor)

### ISSUE THREAD

**Issue by siuster95** [rooseveltframework/roosevelt#392]
In the killValidator, it is suppose to scan a multitude of ports to try and find the one in which the Validator is using if the current port given does not house it. The problem at the moment is that the Validator will go and scan the ports that is assigned to it, but it would scan the port that houses the Validator, but will not find it and later will say that it could not find the Validator on any of the ports that it scanned. There is also the problem that even though the time that is allotted before the script stops looking is set in stone within the script, it will not always follow this. This can be seen in how some of the test will hang for some time before logging that it will stop looking while other tests will immediate say that it will stop looking for the Validator

**Comment by kethinov** [comment]
Adding some specifics to this:

```
npm run kill-validator

⚠️  Could not find validator on port: 8888. Scanning for validator now...
❌  Could not find the validator at this time, please make sure that the validator is running.
```

^ process doesn't exit

**Comment by siuster95** [comment]
My refactoring of the killValidator file is in my killValidator 100%

**Comment by Autre31415** [comment]
Addressed in https://github.com/rooseveltframework/roosevelt/pull/387 and https://github.com/rooseveltframework/roosevelt/pull/413
