### ISSUE TITLE
EADDRNOTAVAIL error catching for server.listen on roosevelt.js

### ISSUE THREAD

**Issue by siuster95** [rooseveltframework/roosevelt#426]
The only way that I had found to trigger this error is by changing the hostname param of server.listen to something that the computer does not have access too. And with how roosevelt is set up, I don't there is a way for the user to change the host, thus making it so that we don't need this error catching

**Comment by Autre31415** [comment]
As @siuster95 has indicated, the server.listen method we're invoking in roosevelt defends against this issue by only allowing `null` or `'localhost'` to be passed as the host argument. Unless that changed in the future I don't see how else this error code can be triggered.
