### ISSUE TITLE
Source Roosevelt configs internally using source-configs instead of internal sourceParams

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#457]
[Edit: the original bug is solved, but the discussion evolved into a new issue that's more like a feature request, thus the title change.]

- ~~The `deployConfig` file should have a `rooseveltConfig` section in it, but may have other config options that are app-specific which roosevelt should ignore. roosevelt should only care about the configs inside of the `rooseveltConfig` section of the file, similar to how it sources configs from package.json.~~
- ~~`deployConfig` settings should override package.json, and env vars, but not command line flags.~~
- ~~`deployConfig` should be able to be set not just from package.json but also env var or command line flag.~~

[Latest:]

The [source-configs](https://github.com/rooseveltframework/source-configs) module can be used to replace much of the logic in sourceParams and possibly sourceFlags.

**Comment by kethinov** [comment]
i believe this is fixed now. @alallier reopen if it isn't

**Comment by alallier** [comment]
Any changes/commits I can view that point to this being solved?

**Comment by kethinov** [comment]
I did a code search on the param and it no longer is set opposite to what our prior discussion implied. It appears to be filtering through sourceParams correctly now.

**Comment by alallier** [comment]
Editing to make what I wanted more clear. I kinda had two conflating issues here I guess. The edit should make things more clear

**Comment by kethinov** [comment]
If we need a deployment level override for one setting, it's reasonable we need one for many more. At this point, what we really need is a rooseveltConfig.json that can be optionally distributed on a per deployment basis which overrides everything in package.json's rooseveltConfig.

**Comment by kethinov** [comment]
(Only the params supplied in the optional file would override package.json, if one is missing, sourceParams would take it from package.json instead.)

**Comment by alallier** [comment]
How would they play with application level deployment files. Tight integration or merging of these things would/could be nice

**Comment by kethinov** [comment]
The idea is the new config file would supersede everything and wouldn't necessarily have to live in your app folder. You could configure package.json to look for the file somewhere and if it's present in the filesystem on your target system, it will source any params set there as higher priority than anything else (similar to env var or command line priority). If the file is not present, it uses the package.json-level defaults.

This seems more scalable than adding dozens of command line or env var flags. Sure some command line or env var flags are useful, but the logic behind your issue seems to imply these are gonna start to pile up, so organizing them in one deployConfig.json or whatever we call it seems the better way to go.

**Comment by alallier** [comment]
Yep got that and agree with it. I was asking if application has it's own deploy config file and roosevelt has it's own would you see those two files being pointed to separately on app startup. Or could you put in specific new config items for your app and have Roosevelt parse them and provide them back to the application?

**Comment by kethinov** [comment]
This file would be roosevelt-specific and sourced at the framework level. If your app has its own concept of this, it would presumably get sourced later because the roosevelt stuff generally happens first.

**Comment by alallier** [comment]
That is what I was trying to get at in my previous comments

**Comment by alallier** [comment]
@kethinov I'll let you edit the title and description as necessary.

**Comment by alallier** [comment]
It would be nice to be able to specify the deploy file location via command line or ENV variable as well

**Comment by kethinov** [comment]
Yeah good point. Or command line flag.
