### ISSUE TITLE
Issue with graceful shutdown when multi-threading

### ISSUE THREAD

**Issue by mulligan121** [rooseveltframework/roosevelt#483]
When the --cores command line flag is in place and you try and do a graceful shutdown with `CTRL` + `C` it throws an error on Windows and Ubuntu. ~~~It seems to work fine on Mac though~~~ After further testing I do replicate this on Mac as well. Although I will note that the shutdown still works.

Ubuntu:
![cores2](https://user-images.githubusercontent.com/3014282/42044980-665955ae-7ac8-11e8-9159-3096e693f6d5.png)

Windows:
![cores2](https://user-images.githubusercontent.com/3014282/42045303-35e4c6aa-7ac9-11e8-85ba-e4a9c6a7035b.PNG)

**Comment by Autre31415** [comment]
Good find, and good work fixing it!
