### ISSUE TITLE
Namespace env variables

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#504]
As we start to accumulate env variables it will be nice to create a namespace scheme for them.

`ROOSEVELT_SET_SOMETHING` can be kinda long

`RS_SET_SOMETHING` is better and covers that case.

Either format works but we should pick one and stick with it as having a namespace has a lot of advantages

**Comment by kethinov** [comment]
I believe this is already the case. A quick scan of the docs and code does not reveal any custom env vars that aren't namespaced under `ROOSEVELT_`

As for short vs long, long is better. We don't want the name to conflict with something else on the system used by some other app. Remember: these are global to the whole OS.

Reopen if you find an example of a nonconforming env var present in the code that I missed though.
