### ISSUE TITLE
Parse command line inputs and return

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#516]
It would/could be useful to parse _all_ command line arguments and return them in a object for Roosevelt applications. This removes the need for Roosevelt applications to use custom and/or third party modules to do this in their application layer

Credit to Benjamin Lannon for this idea.

**Comment by kethinov** [comment]
I'm not sure this needs to be a roosevelt feature. Why not just use something like [command-line-args](https://www.npmjs.com/package/command-line-args) on your app and call it good? It looks relatively straightforward. Is there a compelling reason why this feature needs to be baked into roosevelt itself?

**Comment by kethinov** [comment]
Closing this. Reopen if you think it's still an issue.

**Comment by alallier** [comment]
I think the reason to put this in Roosevelt is because there are two disjoint command line arguments. What Roosevelt uses and what the application will uses. So Roosevelt parses command line arguments and makes them available and then we have to ship our own command line argument parser. So these two things are disjoint, manual checks have to be instituted to make sure command line arguments don't conflict etc.

If Roosevelt parsed command line arguments it could check for conflicts, return **one** array of command line arguments being used, and it's just nice to have as a built in feature so you don't have to ship your own command line argument parser every time.

For those reasons I'm going to re-open this. If that isn't compelling enough, you can close it again

**Comment by kethinov** [comment]
I think you're conflating a couple things here. What roosevelt does is listen for its own command line flags and acts on them if they are present. If there are other command line flags present, it ignores them.

The idea of building a complete list of everything in argv at the roosevelt layer and then trying to deconflict with custom flags is interesting though. I'm not sure how we would go about it or exactly what problem it would solve. Are you envisioning something specific?

**Comment by kethinov** [comment]
Closing this. Reopen if you can provide a specific scenario that makes a good case for why we should bundle a command line parser and not expect app developers to do this themselves if they need it.

Also I think a lot of the potential utility discussed here might be handled by source-configs anyway.
