### ISSUE TITLE
Suggestion: Add Octobox github app to roosevelt org

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/roosevelt#548]
[Octobox](https://octobox.io/) is a web app that displays an inbox for your GitHub notifications. By default, issues & PRs which you wish to be notified about appear in the app. items will only appear stating whether they are an issue or PR, the name of the item, and the way it was added (subscribed, mention, etc). That said, Octobox has a [Github App](https://github.com/apps/octobox) which can be added to individual repos or entire users / orgs. As seen below, it brings more details to the application:

<img width="1392" alt="screen shot 2018-10-14 at 10 00 50 am" src="https://user-images.githubusercontent.com/3685876/46917737-4090a500-cf98-11e8-8604-f42de81af2eb.png">

* Issue / PR status is shown
* Labels & CI content is added
* Author of the issue / PR will be displayed

I propose adding the Octobox GitHub app onto the rooseveltframework org to improve the experience of triaging issues for related projects. The only permissions it needs is read access to the repo's issues & PRs and it does not change anything in the UI of the repos so if you don't use Octobox, the change will be invisible.

**Comment by kethinov** [comment]
Done.
