### ISSUE TITLE
README Update: Other ways to run roosevelt apps

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#59]
README section [other ways to run roosevelt apps](https://github.com/kethinov/roosevelt#other-ways-to-run-roosevelt-apps) needs updating to reflect changes that have been made over the past year

**Comment by kethinov** [comment]
I made some changes to this. Can you take a look at this section of the docs and lemme know if there's anything else you think needs to be there? https://github.com/rooseveltframework/roosevelt#install-roosevelt-and-create-an-app

**Comment by alallier** [comment]
Looks good to me. Probably can close now
