### ISSUE TITLE
Unit Tests occasionally doesn't close Roosevelt Test App which breaks CI

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/roosevelt#618]
Sometimes the tests don't fully shutdown the test app after each test passes or fails and then leaves the process running which causes new tests to break because the port is being used.

Here's an instance when this happens: https://travis-ci.org/rooseveltframework/roosevelt/jobs/474889200

**Comment by reecer62** [comment]
Looks like that job ended up being rerun and passes. Here is a screenshot of what this issue is referring to

![oof](https://user-images.githubusercontent.com/17727106/58882034-6abee080-86a9-11e9-8402-e0defc4b8bcc.PNG)

**Comment by reecer62** [comment]
https://travis-ci.org/rooseveltframework/roosevelt/jobs/530778154

**Comment by kethinov** [comment]
Reopen this if you can find a reliable way to reproduce.
