### ISSUE TITLE
Move the HTML validator functionality to its own module

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#708]
Move the HTML validator functionality to its own module.

Right now the validator is set to only run in development mode which makes plenty of sense. But it would be nice to create a new module to house this code, so that when we do a `npm install --production` the code for the validator will not be present on the system.

This will help remove code delivered in the production environment that we don't care about, and limit possible security concerns of having code that spawns and kills a process on the system.

**Comment by kethinov** [comment]
I think the simplest way to do this would be move vnu-jar to devdeps and then put all the code in htmlValidator.js behind an "if dev mode" flag.

**Comment by alallier** [comment]
It currently is encapsulated by a prod check.

I suppose that would be fine if we also moved the other dependencies that the validator needs into dev like `fkill`

**Comment by kethinov** [comment]
Yeah, the scope of this issue should be moving all deps that are only required in dev mode into devdeps and altering the code accordingly to prevent them from being required in prod mode.

**Comment by alallier** [comment]
Agreed

**Comment by alallier** [comment]
@Autre31415 are there any other dependencies that also fall into this same use case?

**Comment by alallier** [comment]
Re-opening due to rollback in #715

**Comment by kethinov** [comment]
The modularization of htmlValidator.js was preserved in the partial rollback. If any devDependencies are missing, the app will not crash in production mode.
