### ISSUE TITLE
Make config auditor smarter

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#719]
The config auditor is great but it needs to be a little smarter.

Specifically when it is checking for extra params it has to check against a value that represents the largest possible option.

For example, the HTTPS config used to look like this. (This is still what the yeoman generator will give you for example)

```json
"https": {
  "enable": false,
  "httpsOnly": false,
  "httpsPort": 43733,
  "pfx": false,
  "keyPath": "null",
  "passphrase": "null",
  "ca": "null",
  "cafile": true,
  "requestCert": false,
  "rejectUnauthorized": false
}
```

But some parts of this configuration are no longer valid. This doesn't error because the configuration auditor checks the key https to see if it is [missing](https://github.com/rooseveltframework/roosevelt/blob/master/lib/scripts/configAuditor.js#L59-L73) (which it isn't) and it checks to see if it is [_extra_(/undefined)](https://github.com/rooseveltframework/roosevelt/blob/master/lib/scripts/configAuditor.js#L76-L81) (which it also isn't because HTTPS is defined).

When doing the config audit we should check against a value that contains all of the possible key/value pairs to flags on items that are outdated.

**Comment by reecer62** [comment]
This is my plan:

Have 3 separate JSON files 

1. defaults.json (currently config.json) 
2. schema.json 
3. deprecated.json

### defaults.json
The purpose of this file would just be to explicitly define default values for different parameters.

### schema.json
The purpose of this file would be to add a lot of enhancements to the auditor. Each param would have its own metadata, the following fields would be included:

1. type: can be number, integer, string, boolean, array, object or null
check that the param's value matches the specified type
2. required: can be true or false
if required, check that the param is specified and if it isn't then log that there is a missing param
3. description: describe param
describes what param is
4. commandLineArg: command line arguments to listen for that will set this param
can set this param from the command line using this specified flag
5. envVar: environment variables to look for that will set this param
can set this param using an env var
6. properties: an array of objects, the params contained within an object
allows for multiple layers of objects in schema

(numbers 4 and 5 would be relevant to #457)

### deprecated.json
The purpose of this file would be to move any parameters that got deleted or renamed into this file
For example, in the https object, if you had this:
`https: {
    port: 3000,
    ...
}`
And in the deprecated file you had this:
`https: {
    port: "use httpsPort",
    ...
}`
The config auditor would log a message about the param being outdated, and if the auditor couldn't find the param in the schema or the deprecated file, it would log that there is an extra param that can be removed.

With these files, the config auditor would be able to check sublayers of objects and be able to check for outdated configurations. However, if a param was removed or changed, it would be up to whoever changed that param to update that info in these files.

**Comments/suggestions would be much appreciated.**

**Comment by alallier** [comment]
A few thoughts:

## Schema file

I'm trying to figure out how the defaults file and schema can go hand in hand to prevent duplication. Could the default file not just declare null on all the values it doesn't want to define? So that we don't have to have two files. I feel there is a sexier solution lurking here

## deprecated

The deprecated file is really nice, it's a bit more overhead for the maintainers. In this case though could we just log a general error if something unrecognized in the config something like "unknown/possible deprecated key found in package.json"

# Numbers 4 & 5

#457 is a larger effort and out of the scope of this issue

**Comment by Autre31415** [comment]
After extensive discussion we've come to the conclusion that the most sustainable way to get all the features we want into the auditor will be by hard coding it rather than by using a schema.

While normally the default would be to make a feature like this as dynamic as possible with a schema, the Roosevelt config has grown so much and has such a dizzying array of edge cases it would actually be considerably *more* work to schema it all as opposed to handling each param by hand.

As such, our vision of the config auditor would be for it to look more like [this](https://github.com/rooseveltframework/roosevelt/blob/master/lib/sourceFlags.js#L33) going forward. This will allow us to hand tailor each param to handle all of its possible values (Including ones that we don't currently track).
