### ISSUE TITLE
Script to remove dependencies only needed in dev mode for production builds

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#720]
The devDependencies approach attempted in https://github.com/rooseveltframework/roosevelt/issues/708 turned out to be problematic, so only half a solution was implemented. If any dependencies only needed for dev mode are missing, the app will not crash in production mode. That is progress, but we still need a convenient way to actually remove dev-only dependencies from apps without having to manually identify and remove them. After discussing this with @alallier, we propose the following:

1. Make a whitelist of (direct) dependencies that are only needed in dev mode.
2. Explore feasibility of using [npm uninstall](https://docs.npmjs.com/cli/uninstall) to remove them at the app level.
3. For npm uninstall to be considered feasible, the removal should remove both the direct dependency and its subdependencies.
4. Crucially, it should *not* remove subdependencies that are shared with other dependencies that are *not* being removed.

Simplified example:

SimpliRoosevelt dependency graph:

1. Foo: depends on Bar.
2. Baz: depends on Bar and Zog.

If we use npm uninstall on Baz only, the behavior we want is for it to remove Baz and Zog because Zog is a dependency of Baz only. But it should *not* remove Bar because Bar is a dependency of Foo, which we are not removing.

If npm uninstall functions this way (or a similar npm command functions this way), then it would be pretty trivial for us to maintain a script that can remove deps that are not needed in production mode.

**Comment by kethinov** [comment]
An alternative approach we are exploring:

1. Move the dev mode dependencies back to devDeps
2. Provide a special script to force the installation of roosevelt's devDeps in parent projects that use roosevelt as a dependency for development purposes only.
3. Thus, by default, `npm i` will only install deps that are necessary to run the app in prod mode, making it easy to distribute apps with smaller footprints.

**Comment by kethinov** [comment]
After discussing this with @Autre31415, we believe a hybrid of these two approaches is called for:

1. Implement both approaches as npm scripts. One called `npm run dev-install` to install the devDeps, another called `npm run dev-prune` to remove the devDeps.
2. We can avoid needing the user to explicitly run the `npm run dev-install` command by running it automatically in a npm postinstall script. This way the developer experience of just running `npm i` to install dependencies (including roosevelt's devDeps) does not change.
3. The postinstall script can also scan for the presence of an environment variable `ROOSEVELT_DEPLOYMENT` that indicates deployment context. If this environment variable is present, the postinstall script will skip running `npm run dev-install` by default, resulting in no devDeps being installed, and thus the desired smaller footprint.

**Comment by alallier** [comment]
Sounds great to me. I was going to recommend the post install method yesterday but got bogged down. Happy to see you arrived there anyways

**Comment by alallier** [comment]
FWIW I'm surprised something like this isn't offered by npm natively
