### ISSUE TITLE
Tests fail in node 12

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#726]

**Comment by reecer62** [comment]
The first test that fails is in CSS Section Tests. In Node 12, this PR was merged https://github.com/nodejs/node/pull/27109. What this did was set the compact and breakLength to default values. So this line:

> `(app) => { return { versionCode: (app) => { return 1 }, parse: (app, fileName) => { return 1 } } }`

was broken up and was splitting up the code into multiple lines. This caused the code to have invalid syntax which gave an error during the test.
