### ISSUE TITLE
Consider expanding browserify api to support plugins like tinyify

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/roosevelt#736]
[tinyify](https://github.com/browserify/tinyify) is a browserify plugin that compiles the JS bundle within the context of browserify's params, and does so by throwing a whole bunch of various compression tools at it (Including uglify) to make the bundle even smaller than it would be just throwing uglify or closure at it alone.

**Comment by kethinov** [comment]
This should be worked on along with this at the same time: https://github.com/rooseveltframework/roosevelt/issues/297
