### ISSUE TITLE
Run frontend reload on HTML validator error page

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#738]

**Comment by fboechats** [comment]
Can I work on this feature??

**Comment by kethinov** [comment]
Go ahead! Should be pretty easy to fix. As far as I can tell, all that is needed is to remove `res.statusCode === 200` from [this line](https://github.com/rooseveltframework/roosevelt/blob/master/lib/injectReload.js#L8).

**Comment by fboechats** [comment]
Sure, I will send a pr with this fix
