### ISSUE TITLE
HTML Validator issues when proxy is set

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#749]
## Server logs:

```
Error: Invalid protocol: some-proxy.com:
    at Request.init (/Users/lalliera/Work/some-project/node_modules/roosevelt/node_modules/request/request.js:458:31)
    at new Request (/Users/lalliera/Work/some-project/node_modules/roosevelt/node_modules/request/request.js:127:8)
    at request (/Users/lalliera/Work/some-project/node_modules/roosevelt/node_modules/request/index.js:53:10)
    at Promise (/Users/lalliera/Work/some-project/node_modules/roosevelt/node_modules/html-validator/lib/validate.js:9:5)
```

## Client:

Shows unable to connect to validator.

## Other
Everything is fine if you unset any proxy ENV variables in terminal.

**Comment by alallier** [comment]
Upon further investigation I realized my `NO_PROXY` ENV variable was not being setup properly.

I looked to see if it was possible to hardcode localhost to the ignore list in request but it seems that is not an available option.

The only action item here I could mention is: It might be worth adding a note in the README specifically talking about proxies and the need for a NO_PROXY ENV variable. And the reason is, is because the error shown doesn't exactly point of the problem. We scratched our heads up for awhile upon seeing it the first time.

**Comment by kethinov** [comment]
Offline discussion resulted in the following proposed solution:

1. Check if `HTTP_PROXY` and/or `HTTPS_PROXY` env vars exist / are not empty.
2. If 1 is true, check to see if `NO_PROXY` env var has "localhost" in it.
3. If 2 is false, disable the HTML validator and display a warning to the console that explains the HTML validator feature cannot be used when the system has a system-wide proxy set without localhost defined as an exception via `NO_PROXY`.
