### ISSUE TITLE
Expose port as express variable

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#764]
Exposing the port the server running on would be useful for when setting up other things in applications that will rely on the port the server is running on.

https://github.com/rooseveltframework/roosevelt#express-variables-exposed-by-roosevelt

**Comment by kethinov** [comment]
It was possible to do this in Express 3 by getting a reference to the Express app and querying `app.address().port`, but it seems they have removed this.

I was about to label this a bug, but on closer examination I'm not sure it needs to be:

Get the port within a request cycle: `req.socket.address().port`

Do it outside of a request: `app.get('params').port`

**Comment by alallier** [comment]
Ahhh right I can get it out of the params I forgot. That will do. Thank you
