### ISSUE TITLE
Check dependencies will give false positive when using `npm install --only=prod`

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#771]
If you don't have the dev dependencies installed (probably due to having them skipped for a deployment) the [check dependencies module](https://github.com/rooseveltframework/roosevelt/blob/11820b17dc6cc6548a37871717e99be6ce7a91dd/roosevelt.js#L52-L60) that Roosevelt uses will give a false warning

Check dependencies has a [scope option](https://www.npmjs.com/package/check-dependencies#scopelist), during this mode we need to change the scope. Not sure exactly how we will know when we are in this mode, but we could use best guess and tell the user it's best guess given not a single dev dependency is installed. "No development dependencies are installed, this is okay if in a deployment. If you want to install the development dependencies run the script" or something like that.

**Comment by kethinov** [comment]
Offline discussion indicated this can't be reproduced. Reopen if you figure out good steps to reproduce.

**Comment by alallier** [comment]
Sorry, I wasn't simulating the Docker environment we were doing 100%. Install the dependencies with the `--only=prod` flag and you will get the error.

**Comment by Autre31415** [comment]
I agree with the gist of that change with one additional nuance:
- When starting a fresh app, run the auditor *only* if the app is in dev mode, and have checkDeps check all dependencies.
