### ISSUE TITLE
Roosevelt spawns an extra worker thread when using more than one core

### ISSUE THREAD

**Issue by reecer62** [rooseveltframework/roosevelt#819]
The issue: this loop does not account for the master thread when spawning worker threads.
https://github.com/rooseveltframework/roosevelt/blob/ad6ce4fca6454b1a191402252452f0ad16851cb0/roosevelt.js#L411-L414

I put a console log at the beginning of the `roosevelt.js` file that prints out the id of the process running an instance of Roosevelt. Running the app, the master thread runs first and then creates the worker threads. So the master thread and worker threads should all be running an instance of Roosevelt.

The issue is that currently, Roosevelt spawns an extra worker thread when the core count is greater than one.  Sending the app a kill signal can result in worker threads not being killed and causes the shutdown process to hang for a short period of time.

Cores set to 2:
![cpu1](https://user-images.githubusercontent.com/17727106/67898951-ad40f800-fb37-11e9-9c41-640bcbad639f.png)

Cores set to 3:
![cpu2](https://user-images.githubusercontent.com/17727106/67898967-b8942380-fb37-11e9-9426-7026d7676835.png)
Killing the app:
![cpu3](https://user-images.githubusercontent.com/17727106/67898972-ba5de700-fb37-11e9-8063-3fe41d2a8e97.png)

**Comment by kethinov** [comment]
This is obsoleted in 0.23.0.
