### ISSUE TITLE
Add support for external webpack config JS file 

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#879]
In order to set up babel as described in their [documentation](https://webpack.js.org/loaders/babel-loader/). You have to add configuration like this (to your package.json):

```json
"module": {
  "rules": [
    {
      "test": "/\\.js$/",
      "exclude": "/(node_modules|bower_components)/",
      "use": {
        "loader": "babel-loader",
        "options": {
          "presets": [
            "@babel/preset-env"
          ]
        }
      }
    }
  ]
}
```

The point of concern here is this line:

```json
"test": "/\\.js$/"
```

The webpack configuration needs to be valid regex, but you are unable to set Regex as a value in JSON so this means you end up wrapping it in double quotes. So when this gets passed to Webpack the babel transformatioin will not happen because the _"regex"_ passed to Webpack is `"/\\.js$/"` not `/\\.js$/`.

You can test this out by adding this line right before the [Webpack call](https://github.com/rooseveltframework/roosevelt/blob/28f38ff644598aeeb9a74842acc4de6fa8b603c3/lib/jsBundler.js#L43) when using the above configuration.

```
config.module.rules[0].test = /\.js$/
```

**Workaround**: Configure the JS bundler via constructor

**Comment by alallier** [comment]
I'm happy to work on this I'm just not sure how to make this problem in the future "dynamic". I guess we would have to check if the string contains regex and then convert it to regex before using the config anywhere. A hard check on just this one edge case doesn't sound like the right approach.

**Comment by Autre31415** [comment]
I think the solution for this and issues like this would be allowing a config file to be specified. Post processing the contents of a config is not sustainable.

**Comment by alallier** [comment]
So upon looking closet at the code it looks like this is already supported https://github.com/rooseveltframework/roosevelt/blob/8d07c76675d58652fbe15688c8be340258d050a2/lib/jsBundler.js#L36

Although this doesn't resolve the template literals, so simply grabbing your config from package.json with say `${appDir}` is going to fail

**Comment by Autre31415** [comment]
All template literals in the Roosevelt config are resolved in sourceParams immediately after the configuration is sourced.

**Comment by alallier** [comment]
You are correct but the the linked line in question is sourcing the webpack config wholesale outside of that workflow.

**Comment by alallier** [comment]
Any insight on the closing of this issue?

**Comment by kethinov** [comment]
The feature was already supported.

**Comment by alallier** [comment]
Still a bug with the template literals based on my last comment. I don't have the bug fresh in my head anymore because it's been awhile but I could spin it back up and provide additional details/an example.

**Comment by kethinov** [comment]
Okay yeah go ahead and post a clearer example and reopen.
