### ISSUE TITLE
Return config object on constructor instantiation

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#884]
Roosevelt federates all configs from different areas, config file, `pacakge.json`, constructor, ENVs etc.

It would be nice if Roosevelt returned the config used, so that could be used solely as the point of truth across the instantiated app. Otherwise every app has to check all of the different methods to see what is being used and honor Roosevelt's config hierarchy.

I noticed this in an app I maintain because we were sourcing all config values from the `pacakge.json` and when moving the configs to a Roosevelt config file the app broke. Instead I would like to pass around a Roosevelt config object with the values generated by Roosevelt itself.

**Comment by Autre31415** [comment]
This is exposed via the `params` global express variable documented [here](https://github.com/rooseveltframework/roosevelt#express-variables-exposed-by-roosevelt).

**Comment by alallier** [comment]
That will do it, forgot this was attached to the Express app as I wasn't really concerned with the Express app specifically in this case.

Closing, thanks for the help.
