### ISSUE TITLE
The app should yell at you if you're using a template string in your config and typo it

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#888]
Pulled out my hair out wondering why a template literal didn't resolve in the config. It would be nice to throw a warning if someone provides a template string that is not supported or not found.

**Comment by alallier** [comment]
If approved I'd like to take this one

**Comment by kethinov** [comment]
Go for it!

**Comment by kethinov** [comment]
Fixed in https://github.com/rooseveltframework/roosevelt/pull/1256
