### ISSUE TITLE
Refactor generateFolderStructure to be more intuitive

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#891]
Roosevelt's output for CSS is any directory in the _public_ directory. By [default](https://github.com/rooseveltframework/roosevelt/blob/0.17.0/lib/defaults/config.json#L95) `css`.

The public directory is only made if `generateFolderStructure` is set to `true`. The [default](https://github.com/rooseveltframework/roosevelt/blob/0.17.0/lib/defaults/config.json#L5) is false.

This does not generate an error.

**Comment by Autre31415** [comment]
Roosevelt will not generate `any` artifacts unless `generateFolderStructure` is set to true.

**Comment by kethinov** [comment]
We should rename the param to `generateArtifacts` so that it is clear that nothing will be created if the param is set to false.

We should also display a warning when operations are skilled because of this.

**Comment by kethinov** [comment]
Resolved in 0.20.0

**Comment by lannonbr** [comment]
Are we still interested in printing an error that if this is set to false and you try to generate files in the build artifacts dir (by default `public`) it would comment that it is unable to and you should set `makeBuildArtifacts` in your roosevelt config to true?

**Comment by kethinov** [comment]
It does so now in 0.20.0.

💭  Starting my-roosevelt-sample-app in development mode...
💡  my-roosevelt-sample-app will not generate build artifacts like symlinks, compiled/bundled CSS/JS files, etc because the makeBuildArtifacts parameter is set to false. See Roosevelt API docs for more information about the makeBuildArtifacts parameter.

**Comment by lannonbr** [comment]
Alright sorry my bad, did not see that in the commit
