### ISSUE TITLE
Confusion on higher level `minify` configuration parameter

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#902]
The `minify` key is described as:
> Enables HTML minification as well as the minification step in supporting CSS and JS compilers.

If you set this to false this will not disable the webpack minification. You will have to explicitly modify your webpack configration to stop minification in production mode. Like this:

```js
{
  "bundles": [
    {
      "env": "dev",
      "config": {
        "mode": "development",
        "node": {
          "fs": "empty"
        },
        "entry": "${js.sourcePath}/main.js",
        "output": {
          "path": "${publicFolder}/js"
        },
        "resolve": {
          "modules": [
            "${appDir}",
            "${staticsRoot}",
            "${js.sourcePath}",
            "node_modules"
          ]
        }
      }
    },
    {
      "env": "prod",
      "config": {
        "mode": "production",
        "node": {
          "fs": "empty"
        },
        "entry": "${js.sourcePath}/main.js",
        "output": {
          "path": "${publicFolder}/js"
        },
        "optimization": {
          "minimize": false
        },
        "resolve": {
          "modules": [
            "${appDir}",
            "${staticsRoot}",
            "${js.sourcePath}",
            "node_modules"
          ]
        }
      }
    }
  ]
}
```

So it looks like Webpack would be considered an _"unsupported"_ JS compiler? As this stands it is currently a question.

**Comment by Autre31415** [comment]
This is an oversight in the document. That param only controls html and css minification. We don't want to supercede any webpack config with a Eoosevelt param as there's no way we could cover every possible case with how advanced a webpack configuration can get.

**Comment by alallier** [comment]
Yeah I agree
