### ISSUE TITLE
Determine if multer would be a suitable replacement for formidable

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/roosevelt#916]
We have always utilized the [formidable](https://github.com/node-formidable/formidable) middleware to handle multipart form data, but these days there's new game in town, most notably [multer](https://github.com/expressjs/multer) which is maintained by the express team themselves. We should examine the details of these modules and determine if transitioning over would be worthwhile.

**Comment by kethinov** [comment]
we investigated this finally (only 4 years later) and decided to stick with formidible
