### ISSUE TITLE
Option to disable emojis in logger

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#95]
~~Need to replace emoji with unicode characters Windows command line is actually capable of displaying, or just suppress the graphics in Windows.~~

**Comment by alallier** [comment]
I thought when you originally purposed the emoji thing you weren't going to support Windows, that's why I never filed this.

**Comment by kethinov** [comment]
I honestly thought Windows 10 would support this by now and I didn't even bother to test it there. Was planning to file any complaints from Win8 (or older) users as a wontfix.

**Comment by alallier** [comment]
Nice to note that emojis work in Windows PowerShell

**Comment by kethinov** [comment]
I figured different terminals would produce different results in Windows, which is why I haven't tackled this yet. I suspect the fix will be a lot more complicated than just checking what OS the user is running on and setting a flag of whether or not to display emojis. I'm not sure how to feature test whether or not the shell environment supports emoji or if such a feature test is even possible.

**Comment by kethinov** [comment]
Microsoft is [adding emojis to Windows command line](https://arstechnica.com/gadgets/2018/07/microsoft-is-making-the-windows-command-line-a-lot-better/). I think we can stop worrying about this now.

**Comment by kethinov** [comment]
Since Microsoft is taking so long to add support for this despite the promise of a Windows update and because we all know Windows update adoption is really slow anyway, we should actually do something about this after all.

After some discussions, the consensus is an option in the config to disable emojis in the logger. Presently @mulligan121 is working on it.
