### ISSUE TITLE
Typoing rooseveltConfig results in cryptic error

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#955]
If you add "favicon" to the default rooseveltConfig but typo it like "favicon:" "blah" or other various ways of typoing it, you will get an unhelpful errors like `(node:63854) UnhandledPromiseRejectionWarning: Error: No default engine was specified and no extension was provided.`

We should handle it and print a useful error to the console.

**Comment by Autre31415** [comment]
It's possible that this work may need to extend into source-configs itself.

**Comment by lannonbr** [comment]
Filed an issue in source-configs for this: rooseveltframework/source-configs#202
