### ISSUE TITLE
Strange https redirect bug in prod mode only

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#964]
- Create sample app
- Start it in prod mode
- Instead of visiting http://localhost:43711, visit http://[your IP]:43711
- You will be redirected to the same URL, but with HTTPS, and the page will not load because of a SSL error.

**Comment by Autre31415** [comment]
Helmet 4.0 [changed the default settings to include a content security policy](https://github.com/helmetjs/helmet/issues/249), so an app developer either needs to configure it for their domain, or disable csp via:

```
"helmet": {
    "contentSecurityPolicy": false
  }
```
