### ISSUE TITLE
Roosevelt doesn't listen to NODE_ENV as stated in the README

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#970]
The Roosevelt [README](https://github.com/rooseveltframework/roosevelt/tree/5ad71bd9e578dc5898dc6508b05d7f1327bc353b#recognized-environment-variables) states that the app listens to `NODE_ENV` to set the app to `production` or `development`

I did a global search in the code base and it only listens to params to set the app mode, these ENVs are not honored. https://github.com/rooseveltframework/roosevelt/blob/master/lib/sourceParams.js#L407-L417

I noticed this a long time ago but never looked into it until now so I can't tell you the last time it was working properly (if at all).

**Comment by kethinov** [comment]
Express might do it on its own, which is what this relies on. But I don't recall.

**Comment by alallier** [comment]
They do respond to that ENV and do certain things https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production but more importantly is Roosevelt never checks the value of the ENV. So if I set NODE_ENV to `development` the else condition never fires and minifcation happens as Roosevelt is only checking the params and never check to see if the ENV is already defined
