### ISSUE TITLE
Roosevelt Config not merging nested config fields

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/roosevelt#982]
Say you want to turn the verbose mode on for the logging, I tried adding this to my rooseveltConfig.json as such:

```json
{
  "logging": {
    "methods": {
      "verbose": true
    }
  }
}
```

But what happened was it removed all of the other nested fields in the logging methods (`http`, `info`, etc), so for nested objects you currently need to put the entire object in. What I'm curious if we could add a feature to merge them so if you want to turn on the verbose mode or any nested field, you don't need to write the entire object alongside it.

**Comment by kethinov** [comment]
@Autre31415 thoughts?

**Comment by Autre31415** [comment]
I'd say there's a good chance this is a bug in source-configs itself, since that is where the config parsing business logic is happening.

**Comment by Autre31415** [comment]
I was wrong about that. This is caused by how the schema is structured for the `logging` param specifically. Though I do wonder if this is intentional due to how this param is capable of holding custom made configuration.

**Comment by kethinov** [comment]
@lannonbr I read through this again and I'm not seeing a problem or a bug here. Is there some kind of problem this causes that I'm missing? Can you give me an example problem we need to solve?

**Comment by lannonbr** [comment]
Here's the reproduction: https://github.com/lannonbr/roosevelt-reproduction-982

The config by default is the following:

```json
{
  "logging": {
    "methods": {
      "http": true,
      "info": true,
      "warn": true,
      "error": true,
      "verbose": false,
    },
  },
}
```

but if I want to switch `verbose` to true, one may think to add it to the `rooseveltConfig.js` by doing the following:

```json
{
  "logging": {
    "methods": {
      "verbose": true
    }
  }
}
```

What happens with that is logging is overriden to only have `verbose: true` and everything else is removed. This may or may not be a bug, but either way it should be documented what happens when you override a default setting.

**Comment by Autre31415** [comment]
While those extra values wouldn't be printed if you logged the config to the console after tweaking it that way, everything would still behave the same way since those are still the defaults in roosevelt-logger regardless of if they are called out specifically or not.
